Load the dataset into a DataFrame df_ipl and display first 5 rows.

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\uktiw\Downloads\Python\IPL2025Batters.csv")

Display shape and column names of the dataset.

In [3]:
df.shape

(156, 14)

In [4]:
df.head()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37

In [8]:
print(df.columns)

Index(['Player Name', 'Team', 'Runs', 'Matches', 'Inn', 'No', 'HS', 'AVG',
       'BF', 'SR', '100s', '50s', '4s', '6s'],
      dtype='object')

Display only "Player Name" and "Runs" columns.

In [11]:
print(df[['Player Name','Runs']])

           Player Name  Runs
0        Sai Sudharsan   759
1    Surya Kumar Yadav   717
2          Virat Kohli   657
3         Shubman Gill   650
4       Mitchell Marsh   627
..                 ...   ...
151      Khaleel Ahmed     1
152       Mohit Sharma     1
153   Donovan Ferreira     1
154      Digvesh Singh     1
155     Manoj Bhandage     1

[156 rows x 2 columns]

Display data types using info().

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player Name  156 non-null    object
 1   Team         156 non-null    object
 2   Runs         156 non-null    int64
 3   Matches      156 non-null    int64
 4   Inn          156 non-null    int64
 5   No           156 non-null    int64
 6   HS           156 non-null    object
 7   AVG          156 non-null    object
 8   BF           156 non-null    int64
 9   SR           156 non-null    float64
 10  100s         156 non-null    int64
 11  50s          156 non-null    int64
 12  4s           156 non-null    int64
 13  6s           156 non-null    int64
dtypes: float64(1), int64(9), object(4)
memory usage: 17.2+ KB

Select players who scored more than 500 runs.

In [17]:
df[df['Runs']>500]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
8,K L Rahul,DC,539,13,13,3,112*,53.90,360,149.72,1,3,52,21
9,Jos Buttler,GT,538,14,13,4,97*,59.78,330,163.03,0,5,52,24
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40

In [49]:
df[df['Runs']>500,["Player Name"]]

InvalidIndexError: (0       True
1       True
2       True
3       True
4       True
       ...
151    False
152    False
153    False
154    False
155    False
Name: Runs, Length: 156, dtype: bool, ['Player Name'])

Select "Player Name" and "SR" where SR > 150 using loc.

In [20]:
df.loc[df["SR"]>150, ["Player Name", "SR"]]

             Player Name      SR
0          Sai Sudharsan  156.17
1      Surya Kumar Yadav  167.91
3           Shubman Gill  155.87
4         Mitchell Marsh  163.70
5           Shreyas Iyer  175.07
6       Yashasvi Jaiswal  159.71
7      Prabhsimran Singh  160.52
9            Jos Buttler  163.03
10       Nicholas Pooran  196.25
11      Heinrich Klaasen  172.69
12         Priyansh Arya  179.24
14       Abhishek Sharma  193.39
16             Phil Salt  175.98
17           Riyan Parag  166.52
19        Ryan Rickelton  150.97
20           Travis Head  162.60
23          Ishan Kishan  152.58
24        Shashank Singh  153.50
26           Dhruv Jurel  156.33
31        Tristan Stubbs  150.75
33   Sherfane Rutherford  157.29
35           Josh Inglis  162.57
37            Axar Patel  157.48
38         Jitesh Sharma  176.35
39   Vaibhav Suryavanshi  206.55
40            Naman Dhir  182.60
41      Devdutt Padikkal  150.60
42          Sunil Narine  170.83
43          Ayush Mhatre  188.97
45          Aniket Verma  166.19
47         Dewald Brevis  180.00
48         Hardik Pandya  163.50
49           Nitish Rana  161.94
50           Rinku Singh  153.73
51       Ashutosh Sharma  160.62
53            Karun Nair  172.17
56             Tim David  185.14
58         Shahrukh Khan  179.00
59         Andre Russell  163.72
60           Abdul Samad  176.34
61        Marcus Stoinis  186.04
65          Vipraj Nigam  179.74
67     Washington Sundar  166.25
68       Ruturaj Gaikwad  150.61
69          Sameer Rizvi  153.16
74         Shubham Dubey  160.60
75         Rahul Tewatia  167.79
76           Pat Cummins  167.24
80        Jonny Bairstow  184.78
84      Romario Shepherd  291.66
85           Urvil Patel  212.50
86         Jacob Bethell  171.79
103           Avesh Khan  175.00
105         Kusal Mendis  200.00
108       Gerald Coetzee  154.54
109        Jamie Overton  214.28
124        Kwena Maphaka  400.00
125       Raj Angad Bawa  200.00
129           Akash Deep  300.00
137      Lockie Ferguson  400.00

Select players from team "RCB".

In [24]:
df.loc[df['Team'] == "RCB"], ["Player Name","Team"]

(           Player Name Team  Runs  Matches  Inn  No   HS    AVG   BF      SR  \
 2          Virat Kohli  RCB   657       15   15   3  73*  54.75  454  144.71
 16           Phil Salt  RCB   403       13   13   1   65  33.58  229  175.98
 28       Rajat Patidar  RCB   312       15   14   1   64  24.00  217  143.77
 38       Jitesh Sharma  RCB   261       15   11   4  85*  37.29  148  176.35
 41    Devdutt Padikkal  RCB   247       10   10   1   61  27.44  164  150.60
 56           Tim David  RCB   187       12    9   6  50*  62.33  101  185.14
 72    Liam Livingstone  RCB   112       10    8   1   54  16.00   84  133.33
 73       Krunal Pandya  RCB   109       15    7   1  73*  18.17   86  126.74
 77      Mayank Agarwal  RCB    95        4    4   1  41*  31.67   64  148.43
 84    Romario Shepherd  RCB    70        8    3   1  53*  35.00   24  291.66
 86       Jacob Bethell  RCB    67        2    2   0   55  33.50   39  171.79
 112  Bhuvneshwar Kumar  RCB    14       14    6   3    8   4.67   25   56.00
 138         Yash Dayal  RCB     4       15    3   1    3   2.00    8   50.00
 155     Manoj Bhandage  RCB     1        1    1   0    1   1.00    4   25.00

      100s  50s  4s  6s
 2       0    8  66  19
 16      0    4  48  22
 28      0    2  25  14
 38      0    1  24  17
 41      0    2  21  14
 56      0    1  16  14
 72      0    1   4   9
 73      0    1   9   4
 77      0    0  10   2
 84      0    1   5   7
 86      0    1   9   3
 112     0    0   1   0
 138     0    0   0   0
 155     0    0   0   0  ,
 ['Player Name', 'Team'])

Select players where Runs > 600 and display only "Player Name" and "Team".

In [26]:
df.loc[df['Runs']>600, ["Player Name","Team"]]

         Player Name  Team
0      Sai Sudharsan    GT
1  Surya Kumar Yadav    MI
2        Virat Kohli   RCB
3       Shubman Gill    GT
4     Mitchell Marsh   LSG
5       Shreyas Iyer  PBKS

Select players where 50s >= 5.

In [37]:
df[df['50s']>=5]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28
9,Jos Buttler,GT,538,14,13,4,97*,59.78,330,163.03,0,5,52,24
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40
13,Aiden Markram,LSG,445,13,13,0,66,34.23,299,148.82,0,5,38,22

Select players with at least one century (100s > 0).

In [40]:
df[df['100s']>0]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
8,K L Rahul,DC,539,13,13,3,112*,53.90,360,149.72,1,3,52,21
11,Heinrich Klaasen,SRH,487,13,13,2,105*,44.27,282,172.69,1,1,42,25
12,Priyansh Arya,PBKS,475,17,17,0,103,27.94,265,179.24,1,2,55,25
14,Abhishek Sharma,SRH,439,14,13,0,141,33.77,227,193.39,1,2,46,28
23,Ishan Kishan,SRH,354,14,13,3,106*,35.40,232,152.58,1,1,33,15
36,Rishabh Pant,LSG,269,14,13,2,118*,24.45,202,133.16,1,1,23,16
39,Vaibhav Suryavanshi,RR,252,7,7,0,101,36.00,122,206.55,1,1,18,24

Select players where Runs > 500 AND SR > 140.

In [41]:
df[(df['Runs']>500) & (df['SR']>140)]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
8,K L Rahul,DC,539,13,13,3,112*,53.90,360,149.72,1,3,52,21
9,Jos Buttler,GT,538,14,13,4,97*,59.78,330,163.03,0,5,52,24
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40

Select players where Team = "MI" AND Runs > 400.

In [44]:
df[(df["Team"]=='MI') & (df["Runs"]>400)]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
15,Rohit Sharma,MI,418,15,15,1,81,29.86,280,149.28,0,4,41,22

Sort players by Runs in descending order.

Difference between df["Runs"] and df[["Runs"]]

In [46]:
df["Runs"]

0      759
1      717
2      657
3      650
4      627
      ...
151      1
152      1
153      1
154      1
155      1
Name: Runs, Length: 156, dtype: int64

In [47]:
df[["Runs"]]

     Runs
0     759
1     717
2     657
3     650
4     627
..    ...
151     1
152     1
153     1
154     1
155     1

[156 rows x 1 columns]