In [17]:
import pandas as pd

# Create dataset
data = {
    "Student": ["A","B","C","D","E","F","G","H","I","J"],
    "Passed": ["Yes","No","Yes","Yes","No",
               "Yes","Yes","No","Yes","Yes"]
}

df = pd.DataFrame(data)

df

  Student Passed
0       A    Yes
1       B     No
2       C    Yes
3       D    Yes
4       E     No
5       F    Yes
6       G    Yes
7       H     No
8       I    Yes
9       J    Yes

In [18]:
total = len(df)

In [19]:
df[df["Passed"]=="Yes"]

  Student Passed
0       A    Yes
2       C    Yes
3       D    Yes
5       F    Yes
6       G    Yes
8       I    Yes
9       J    Yes

In [20]:
passed = len(df[df["Passed"]=="Yes"])

In [21]:
prob_passed = passed/total
print('Prob of Passed', prob_passed)

Prob of Passed 0.7

In [22]:
failed = len(df[df["Passed"]=="No"])

In [23]:
prob_failed = failed/total
print('Prob of Failed', prob_failed)

Prob of Failed 0.3

In [24]:
import pandas as pd

# Dataset
data = {
    "Student": ["A","B","C","D","E","F"],
    "Gender": ["Boy","Boy","Boy","Girl","Girl","Girl"],
    "Passed": ["Yes","No","Yes","Yes","No","Yes"]
}

df = pd.DataFrame(data)

df

  Student Gender Passed
0       A    Boy    Yes
1       B    Boy     No
2       C    Boy    Yes
3       D   Girl    Yes
4       E   Girl     No
5       F   Girl    Yes

In [25]:
total = len(df)

In [26]:
total

6

In [28]:
boys = len(df[df["Gender"]=="Boy"])
boys

3

In [30]:
passed = len(df[df["Passed"]=="Yes"])
passed

4

In [34]:
boy_passed = len(df[(df["Gender"]=="Boy") & (df["Passed"]=="Yes")])

In [35]:
prob_boy_passed = (boys + passed - boy_passed)/total

In [36]:
prob_boy_passed

0.8333333333333334

In [38]:
girls =  len(df[df["Gender"]=="Girl"])
girls

3

In [39]:
passed = len(df[df["Passed"]=="Yes"])

In [40]:
girl_passed = len(df[(df["Gender"]=="Girl") & (df["Passed"]=="Yes")])
girl_passed

2

In [41]:
prob_girl_passed = (girls + passed - girl_passed)/total

In [42]:
prob_girl_passed

0.8333333333333334

### girls and failed

In [43]:
girls =  len(df[df["Gender"]=="Girl"])
girls

3

In [44]:
failed = len(df[df["Passed"]=="No"])
failed

2

In [45]:
girl_failed = len(df[(df["Gender"]=="Girl") & (df["Passed"]=="No")])
girl_failed

1

In [48]:
prob_girl_failed = (girl_failed)/total
prob_girl_failed

0.16666666666666666

## Boy and Passed

In [50]:
boys = len(df[df["Gender"]=="Boy"])
boys

3

In [51]:
passed = len(df[df["Passed"]=="Yes"])
passed

4

In [52]:
boy_passed = len(df[(df["Gender"]=="Boy") & (df["Passed"]=="Yes")])

In [53]:
prob_boy_passed = (boy_passed)/total

In [54]:
prob_boy_passed

0.3333333333333333

In [55]:
import pandas as pd

data = {
    "Day": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Weather": ["Hot", "Hot", "Hot", "Cold", "Cold", "Hot", "Cold", "Hot", "Cold", "Hot"],
    "Bought Ice Cream": ["Yes", "Yes", "No", "No", "No", "Yes", "Yes", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)
print(df)

   Day Weather Bought Ice Cream
0    1     Hot              Yes
1    2     Hot              Yes
2    3     Hot               No
3    4    Cold               No
4    5    Cold               No
5    6     Hot              Yes
6    7    Cold              Yes
7    8     Hot              Yes
8    9    Cold               No
9   10     Hot              Yes

## Hot and bought icecream

In [57]:
total = len(df)
total

10

In [64]:
hot = len(df[df["Weather"] == "Hot"])
hot

6

In [67]:
bought = len(df[df["Bought Ice Cream"] == "Yes"])
bought

6

In [70]:
hot_bought_icecream = len(df[(df["Weather"] == "Hot") & (df["Bought Ice Cream"] == "Yes")])
hot_bought_icecream

5

In [71]:
prob_of_hot_and_bought = (hot + bought - hot_bought_icecream)/total

In [72]:
prob_of_hot_and_bought

0.7

# cold and bought icecream

In [73]:
cold = hot = len(df[df["Weather"] == "Cold"])
cold

4

In [74]:
bought = len(df[df["Bought Ice Cream"] == "Yes"])
bought

6

In [75]:
cold_bought_icecream = len(df[(df["Weather"] == "Cold") & (df["Bought Ice Cream"] == "Yes")])
cold_bought_icecream

1

In [78]:
prob_of_cold_and_bought = (cold + bought - cold_bought_icecream)/total
prob_of_cold_and_bought

0.9

# hot or bought

In [81]:
hot_icecream = hot_bought_icecream/total
hot_bought_icecream/total

0.5

## Cold or Bought

In [83]:
cold_icecream =  cold_bought_icecream/total
cold_icecream

0.1