In [1]:
import pandas as pd

data = {
    "Student": ["A","B","C","D","E","F","G","H","I","J"],
    "Cricket": ["Yes","Yes","Yes","No","No","Yes","No","Yes","No","Yes"],
    "Passed": ["Yes","Yes","No","Yes","No","Yes","No","Yes","Yes","No"]
}

df = pd.DataFrame(data)

In [2]:
df

  Student Cricket Passed
0       A     Yes    Yes
1       B     Yes    Yes
2       C     Yes     No
3       D      No    Yes
4       E      No     No
5       F     Yes    Yes
6       G      No     No
7       H     Yes    Yes
8       I      No    Yes
9       J     Yes     No

In [6]:
play_cric= len(df[df['Cricket']=='Yes'])/len(df)

In [7]:
play_cric

0.6

In [8]:
passed = len(df[df['Passed']=='Yes'])/len(df)
passed

0.6

In [16]:
cricket_passed= len(df[(df['Cricket']=='Yes') & (df['Passed']=='Yes')])/len(df)
cricket_passed

0.4

In [14]:
cricket_or_passed = len(df[(df['Cricket']=='Yes') | (df['Passed']=='Yes')])/len(df)

In [15]:
cricket_or_passed

0.8

### probability of passed given he plays cricket

In [19]:
passed_given_cricket = cricket_passed/play_cric
passed_given_cricket

0.6666666666666667

## Bases Theorem- probability of cricket given passed

In [20]:
cricket_given_passed = passed_given_cricket * play_cric/passed

In [21]:
cricket_given_passed

0.6666666666666667

In [22]:
data = {
    "Student": ["A","B","C","D","E"],
    "Study_hours": [2,4,6,8,10]
}

df = pd.DataFrame(data)

In [23]:
df

  Student  Study_hours
0       A            2
1       B            4
2       C            6
3       D            8
4       E           10

In [25]:
mean_value = df['Study_hours'].mean()
mean_value

np.float64(6.0)

In [26]:
df['Deviation'] = df['Study_hours'] - mean_value

In [27]:
df

  Student  Study_hours  Deviation
0       A            2       -4.0
1       B            4       -2.0
2       C            6        0.0
3       D            8        2.0
4       E           10        4.0

In [28]:
df['Absoulte_deviation'] = abs(df['Deviation'])

In [29]:
df

  Student  Study_hours  Deviation  Absoulte_deviation
0       A            2       -4.0                 4.0
1       B            4       -2.0                 2.0
2       C            6        0.0                 0.0
3       D            8        2.0                 2.0
4       E           10        4.0                 4.0

In [38]:
Absolute_mean_deviation = df['Absoulte_deviation'].mean()

In [39]:
Absolute_mean_deviation

np.float64(2.4)